# Generated by Django 4.2.1 on 2023-06-06 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("underdog_id", models.UUIDField(unique=True)),
                ("name", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=2)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nfl.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matchup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.PositiveIntegerField()),
                ("week_num", models.PositiveIntegerField()),
                (
                    "away_team_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_team",
                        to="nfl.team",
                    ),
                ),
                (
                    "home_team_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_team",
                        to="nfl.team",
                    ),
                ),
            ],
        ),
    ]
