# Generated by Django 4.2.1 on 2023-06-06 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nfl", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchup",
            old_name="away_team_code",
            new_name="away_team",
        ),
        migrations.RenameField(
            model_name="matchup",
            old_name="home_team_code",
            new_name="home_team",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="code",
            new_name="id",
        ),
    ]
