# Generated by Django 4.2.1 on 2023-06-05 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("underdog_draft_id", models.UUIDField(editable=False)),
                ("underdog_tournament_id", models.UUIDField(editable=False)),
                ("tournament_title", models.CharField(max_length=50)),
                ("entry_fee", models.PositiveIntegerField()),
                ("total_prizes", models.PositiveIntegerField()),
                ("tournament_size", models.PositiveIntegerField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=3, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("underdog_id", models.UUIDField(editable=False)),
                ("name", models.CharField(max_length=50)),
                ("position", models.CharField(max_length=2)),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exposures.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pick_time", models.DateTimeField()),
                ("pick_num", models.PositiveIntegerField()),
                (
                    "underdog_draft_id",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exposures.draft",
                    ),
                ),
                (
                    "underdog_player_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exposures.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matchup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.PositiveIntegerField()),
                ("week_num", models.PositiveIntegerField()),
                (
                    "away_team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_team",
                        to="exposures.team",
                    ),
                ),
                (
                    "home_team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_team",
                        to="exposures.team",
                    ),
                ),
            ],
        ),
    ]
