# Generated by Django 4.2.1 on 2023-06-09 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="github_id",
            new_name="social_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="google_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="twitter_id",
        ),
    ]
