# Generated by Django 4.2.1 on 2023-06-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_github_id_profile_social_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="social_id",
        ),
        migrations.AddField(
            model_name="profile",
            name="provider_id",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="provider_name",
            field=models.CharField(default="default", max_length=200),
            preserve_default=False,
        ),
    ]
