# Generated by Django 4.2.1 on 2023-06-06 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("nfl", "0002_rename_away_team_code_matchup_away_team_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("underdog_draft_id", models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("entry_fee", models.PositiveIntegerField()),
                ("total_prizes", models.PositiveIntegerField()),
                ("field_size", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Pick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pick_time", models.DateTimeField()),
                ("pick_num", models.PositiveIntegerField()),
                (
                    "underdog_draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="underdog.draft",
                        to_field="underdog_draft_id",
                    ),
                ),
                (
                    "underdog_player_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nfl.player",
                        to_field="underdog_id",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="draft",
            name="underdog_tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="underdog.tournament"
            ),
        ),
        migrations.AddField(
            model_name="draft",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
