# Generated by Django 4.2.1 on 2023-06-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_profile_social_id_profile_provider_id_and_more"),
        ("underdog", "0002_rename_underdog_player_id_pick_underdog_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user.profile"
            ),
        ),
    ]
